name: Update Version, Build and Publish

on:
  push:
    branches: [main]
    paths:
      - 'packages/**'

jobs:
  update-version-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        package:
          - messageflow-core-service
          - messageflow-docs-app
          - messageflow-gateway-service
          - messageflow-web-app
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install

      - name: Update version for ${{ matrix.package }}
        run: |
          cd packages/${{ matrix.package }}
          npm version patch -m "Bump ${{ matrix.package }} to %s"
          git push
          git push --tags

      - name: Build ${{ matrix.package }}
        run: yarn workspace ${{ matrix.package }} build

      - name: Get package version
        id: package-version
        run: echo "VERSION=$(node -p "require('./packages/${{ matrix.package }}/package.json').version")" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./packages/${{ matrix.package }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.package }}:${{ steps.package-version.outputs.VERSION }}
            ghcr.io/${{ github.repository }}/${{ matrix.package }}:latest