name: Update Package Versions

on:
  push:
    branches: [ main ]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Update versions
        run: yarn run update-versions

      - name: Show changes
        run: git diff

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: Bump patch version
          title: 'Bump patch version'
          body: |
            This PR bumps the patch version for all packages in the monorepo.
            
            Automated changes by GitHub Action.
          branch: version-bump
          base: main