name: Update Version and Publish Docker

on:
  push:
    branches: [main]
    paths:
      - 'packages/**'

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        package:
          - messageflow-core-service
          - messageflow-docs-app
          - messageflow-gateway-service
          - messageflow-web-app
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install

      - name: Update version for ${{ matrix.package }}
        run: |
          cd packages/${{ matrix.package }}
          npm version patch -m "Bump ${{ matrix.package }} to %s"
          git push
          git push --tags

      - name: Build ${{ matrix.package }}
        run: yarn workspace ${{ matrix.package }} build

  docker-publish:
    needs: update-version
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        package:
          - messageflow-core-service
          - messageflow-docs-app
          - messageflow-gateway-service
          - messageflow-web-app
    steps:
      - uses: actions/checkout@v4

      - name: Get package version
        id: package-version
        run: echo "VERSION=$(node -p "require('./packages/${{ matrix.package }}/package.json').version")" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Set lowercase repository name
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_LOWER=${REPO_LOWER}" >> $GITHUB_OUTPUT
        id: repo_name

      - name: Set lowercase package name
        run: |
          PACKAGE_LOWER=$(echo "${{ matrix.package }}" | tr '[:upper:]' '[:lower:]')
          echo "PACKAGE_LOWER=${PACKAGE_LOWER}" >> $GITHUB_OUTPUT
        id: package_name

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./packages/${{ matrix.package }}
          file: ./packages/${{ matrix.package }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.repo_name.outputs.REPO_LOWER }}/${{ steps.package_name.outputs.PACKAGE_LOWER }}:${{ steps.package-version.outputs.VERSION }}
            ghcr.io/${{ steps.repo_name.outputs.REPO_LOWER }}/${{ steps.package_name.outputs.PACKAGE_LOWER }}:latest