name: Main Branch CI/CD

on:
  push:
    branches: [main]

jobs:
  determine_changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - id: set-matrix
        run: |
          # Script to determine which apps changed
          # This is a placeholder. You need to implement the logic to detect changes.
          CHANGED_APPS=$(git diff --name-only HEAD^ HEAD | grep '^apps/' | cut -d'/' -f2 | sort -u | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix={\"app\":$CHANGED_APPS}" >> $GITHUB_OUTPUT

  build:
    needs: determine_changes
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.determine_changes.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: yarn install
      - name: Build app
        run: yarn workspace ${{ matrix.app }} build
      - name: Run tests
        run: yarn workspace ${{ matrix.app }} test

  docker_build_and_push:
    needs: [determine_changes, build]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.determine_changes.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/${{ matrix.app }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.app }}:latest,ghcr.io/${{ github.repository }}/${{ matrix.app }}:${{ github.sha }}