name: Pull Request CI

on:
  pull_request:
    branches: [main]
    paths:
      - 'packages/**'

jobs:
  check_for_version_only_changes:
    runs-on: ubuntu-latest
    outputs:
      version_only: ${{ steps.check_changes.outputs.version_only }}
    steps:
      - uses: actions/checkout@v4
      - id: check_changes
        run: |
          if [[ $(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep -v 'package.json') ]]; then
            echo "version_only=false" >> $GITHUB_OUTPUT
          else
            echo "version_only=true" >> $GITHUB_OUTPUT
          fi

  determine_changes:
    needs: check_for_version_only_changes
    if: needs.check_for_version_only_changes.outputs.version_only == 'false'
    runs-on: ubuntu-latest
    outputs:
      changed_packages: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            messageflow-core-service:
              - 'packages/messageflow-core-service/**'
            messageflow-docs-app:
              - 'packages/messageflow-docs-app/**'
            messageflow-gateway-service:
              - 'packages/messageflow-gateway-service/**'
            messageflow-web-app:
              - 'packages/messageflow-web-app/**'

  build:
    needs: [check_for_version_only_changes, determine_changes]
    if: needs.check_for_version_only_changes.outputs.version_only == 'false' && needs.determine_changes.outputs.changed_packages != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ needs.determine_changes.outputs.changed_packages }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: yarn install
      - name: Build ${{ matrix.package }}
        run: yarn workspace ${{ matrix.package }} build
#      - name: Run tests for ${{ matrix.package }}
#        run: yarn workspace ${{ matrix.package }} test