name: Pull Request CI

on:
  pull_request:
    branches: [main]

jobs:
  determine_changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          # Script to determine which apps changed
          # This is a placeholder. You need to implement the logic to detect changes.
          CHANGED_APPS=$(git diff --name-only origin/main...HEAD | grep '^apps/' | cut -d'/' -f2 | sort -u | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix={\"app\":$CHANGED_APPS}" >> $GITHUB_OUTPUT

  build:
    needs: determine_changes
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.determine_changes.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: yarn install
      - name: Build app
        run: yarn workspace ${{ matrix.app }} build
      - name: Run tests
        run: yarn workspace ${{ matrix.app }} test